### ISSUE TITLE
Cosine Needlets fails after removal of "recompute_covmat_for_ndeproj"

### ISSUE THREAD

**Issue by JamesAmato** [jcolinhill/pyilc#13]
When running with CosineNeedlets, I get an "Exception has occurred: AttributeError  'ILCInfo' object has no attribute 'recompute_covmat_for_ndeproj'" at line 1397 in wavelets.py.

I believe it is comes from commit 1db356b which removed the "recompute_covmat_for_ndeproj" flag from inputs.py.

**Comment by fmccarthy** [comment]
Thank you! This was only triggered when files with "save_as: 'fits' " were in the input as it was a problem in the function that created the .fits file names. I removed the line that checks for this in wavelets.py . I hope that fixes the problem.

**Comment by JamesAmato** [comment]
That resolved it. Thank you.
